[template]
prefix = "/swarm-deploy/demoproject/dev"
src = "demoproject-dev.undo.tmpl"
dest = "/data/server/swarm-deploy/temp.cmd/demoproject-dev.undo"
owner = "root"
mode = "0644"
keys = [
  "/undo",
]
reload_cmd = "cd /data/server/swarm-deploy && /bin/bash bin/confd_reload_cmd.sh temp.cmd/demoproject-dev.undo"
