apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pctest1
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: s1.pctest
    http:
      paths:
      - path: /
        backend:
          serviceName: s1
          servicePort: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: s1
  labels:
    app: pctest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pctest1
      task: s1
  template:
    metadata:
      labels:
        app: pctest1
        task: s1
    spec:
      containers:
      - name: pctest1
        image: opera443399/whoami:0.8
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: s1
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: pctest1
    task: s1
