apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pctest2
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: s2.pctest
    http:
      paths:
      - path: /
        backend:
          serviceName: s2
          servicePort: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: s2
  labels:
    app: pctest2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pctest2
      task: s2
  template:
    metadata:
      labels:
        app: pctest2
        task: s2
    spec:
      containers:
      - name: pctest2
        image: opera443399/whoami:0.9
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: s2
  labels:
    app: pctest2
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: pctest2
    task: s2
